# This is my word.
Word: Banana
Number: 42

# Type the name of the language here.
# E.g., en, nl...
Language: en

# Hello, this is a comment!

Boolean: true
Fruits:
  - Banana
  - Apple
  - Strawberry
  - Pear
# Test:
#   Test1:
#   Test2:
#     Test2.1: "" # Path to here = Test.Test2.Test2.1
#   Test3: "" # Path to here = Test.Test3

OpenAI-Key:

Host:
Port:
Database:
Username:
Password:

MongoDB-Username:
MongoDB-Password:

Discord-Bot-Token:
